import { Box, Modal } from '@mui/material';
import { useState } from 'react';

const CREATE = 1;
const EDIT = 2;
const VIEW = 3;

const RSOmodal = (props) => {
    const { mode, rso, updateRSO, open, setModalOpen, allUniversities } = props;

    // Fixed fields, not editable by user
    // Generated by server if empty
    let rsoid = rso ? rso.rsoid : '';
    let uname = rso ? rso.uname : '';
    let uid = rso ? rso.uid : '';
    let unid = rso ? rso.unid : '';

    // Editable by user, if that is the mode.
    const [name, setName] = useState(rso ? rso.name : '');
    const [description, setDescription] = useState(rso ? rso.description : '');
    const [numMembers, setNumMembers] = useState(rso ? rso.numMembers : 0);

    // If creating, will have to select a university.
    // Not changeable in edit mode.
    const [university, setUniversity] = useState(null);

    return (
        <Modal open={open} onClose={() => setModalOpen(false)}>
            <Box
                component="form"
                autoComplete="off"
                onSubmit={(e) => e.preventDefault()}
            >
                <h1>Yo</h1>
            </Box>
        </Modal>
    );
};

export default RSOmodal;
